### ISSUE TITLE
Installed and activated. What next?

### ISSUE THREAD

**Issue by ghost** [bfolliot/feed-importer#1]
Not seeing anything in the WordPress interface after activation. How did you build this? Do I need to find a way to call `getSourceLink()` in the API?

**Comment by ghost** [comment]
Ne pas voir quoi que ce soit dans l'interface WordPress après l'activation. Comment avez-vous construit ceci?

**Comment by jhabdas** [comment]
@bfolliot

**Comment by bfolliot** [comment]
Hi @jhabdas, this plugin is not stable or complete.

Use BFolliot\FeedImporter\Importer to import post from feed.

The getSourceLink method is juste for retrieve the original URL of the post

**Comment by ghost** [comment]
@bfolliot thank you kindly for this glorious little wonder.

**Comment by jhabdas** [comment]
@bfolliot when designing this, did you consider use of [`fetch_feed()`](https://developer.wordpress.org/reference/functions/fetch_feed/) over Zend Importer?

**Comment by jhabdas** [comment]
Oof. Never mind. Dumb question. That method uses Simple Pie 1.3 which only works on ancient versions of PHP.

**Comment by jhabdas** [comment]
Jotting this down for later.

<img width="850" alt="screen shot 2017-06-28 at 3 24 18 pm" src="https://user-images.githubusercontent.com/440298/27625115-0ec9fe0a-5c16-11e7-9806-8414d104dc70.png">

**Comment by ghost** [comment]
FYI https://wordpress.org/plugins/import-xml-feed/
